run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Проверяет неиспользованные ошибки
    - gosimple      # Упрощение кода
    - govet         # Стандартный go vet
    - ineffassign   # Неэффективные присваивания
    - staticcheck   # Статический анализ
    - unused        # Неиспользуемый код
    - gofmt         # Форматирование
    - goimports     # Импорты
    - misspell      # Орфография в комментариях
    - revive        # Быстрый линтер
    - gosec         # Проверка безопасности

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  
  govet:
    enable:
      - shadow    # Проверка shadowing переменных
  
  revive:
    confidence: 0.8
  
  gosec:
    excludes:
      - G104  # Ошибки аудита - мы используем nolint где нужно

issues:
  exclude-rules:
    # Игнорируем ошибки в тестовых файлах
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    # Игнорируем длинные строки в комментариях
    - linters:
        - lll
      source: "^//"
  
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

